version: "3.4"

services:
    mysql:
        container_name: mysql
        image: mysql:8
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-MCIUser}  
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-LuvuubyRK*Jason1258}
        volumes:
            - mysql:/var/lib/mysql/
            - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        networks:
            - my_network

    phpmyadmin:
        container_name: test-phpmyadmin
        image: phpmyadmin/phpmyadmin:4.9
        restart: always
        ports:
            - "8888:80"
        environment:
            PMA_HOST: mysql
        networks:
            - my_network

    server:
        container_name: server
        build:
            context: ./src/springboot-server/
        image: server
        restart: unless-stopped
        ports:
            - "28080:28080"   
        networks:
            - my_network
        environment:
            JAVA_OPTS: ${JAVA_OPTS:- -Xms512m -Xmx512m -Djava.security.egd=file:/dev/./urandom}
            ARGS: --spring.datasource.url=${DATASOURCE_URL:-jdbc:mysql://mysql:3306/MCIUser?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true} --spring.datasource.username=${DATASOURCE_USERNAME:-root} --spring.datasource.password=${DATASOURCE_PASSWORD:-LuvuubyRK*Jason1258}
        depends_on:
            - mysql
    web:
        container_name: web
        build:
            context: ./src/vue-web
        image: web
        restart: unless-stopped
        ports:
            - "80:80"
        networks:
            - my_network
        depends_on:
            - server
volumes:
    mysql:
        driver: local

networks:
    my_network:
        driver: bridge